<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Currency;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [
            ['currency_name' =>'AED United Arab Emirates Dirham ', 'is_status' => 1],
            ['currency_name' =>'AFN  Afghani', 'is_status' => 1],
            ['currency_name' =>'ALL Lek ', 'is_status' => 1],
            ['currency_name' =>'AMD Dram ', 'is_status' => 1],
            ['currency_name' =>'ANG Netherlands Antilles Guilder ', 'is_status' => 1],
            ['currency_name' =>'AOA Kwanza ', 'is_status' => 1],
            ['currency_name' =>'ARS Argentinian Nuevo Peso ', 'is_status' => 1],
            ['currency_name' =>'AUD Australian Dollar ', 'is_status' => 1],
            ['currency_name' =>'AWG Aruban Guilder ', 'is_status' => 1],
            ['currency_name' =>'AZN  New Manats', 'is_status' => 1],
            ['currency_name' =>'BAM Convertible Mark ', 'is_status' => 1],
            ['currency_name' =>'BBD Barbados Dollar ', 'is_status' => 1],
            ['currency_name' =>'BDT Taka ', 'is_status' => 1],
            ['currency_name' =>'BGN  Leva', 'is_status' => 1],
            ['currency_name' =>'BHD Bahraini Dinar ', 'is_status' => 1],
            ['currency_name' =>'BIF Burundi Franc ', 'is_status' => 1],
            ['currency_name' =>'BMD Bermudian Dollar ', 'is_status' => 1],
            ['currency_name' =>'BND Brunei Dollar ', 'is_status' => 1],
            ['currency_name' =>'BOB Boliviano ', 'is_status' => 1],
            ['currency_name' =>'BRL Real ', 'is_status' => 1],
            ['currency_name' =>'BSD Bahamian Dollar ', 'is_status' => 1],
            ['currency_name' =>'BTC bitcoin', 'is_status' => 1],
            ['currency_name' =>'BTN Ngultrum ', 'is_status' => 1],
            ['currency_name' =>'BWP Pula ', 'is_status' => 1],
            ['currency_name' =>'BYR Belarussian Rouble ', 'is_status' => 1],
            ['currency_name' =>'BZD Belize Dollar ', 'is_status' => 1],
            ['currency_name' =>'CAD Canadian Dollar ', 'is_status' => 1],
            ['currency_name' =>'CDF CDF', 'is_status' => 1],
            ['currency_name' =>'CHF Swiss Franc ', 'is_status' => 1],
            ['currency_name' =>'CLP Chilean Peso ', 'is_status' => 1],
            ['currency_name' =>'CNY Yuan Renminbi ', 'is_status' => 1],
            ['currency_name' =>'COP Colombian Peso ', 'is_status' => 1],
            ['currency_name' =>'CRC Costa Rican ColÃƒÂ³n ', 'is_status' => 1],
            ['currency_name' =>'CUP Cuban Peso ', 'is_status' => 1],
            ['currency_name' =>'CVE Escudo Caboverdiano ', 'is_status' => 1],
            ['currency_name' =>'CZK Czech Koruna ', 'is_status' => 1],
            ['currency_name' =>'DJF Djibouti Franc ', 'is_status' => 1],
            ['currency_name' =>'DKK Danish Krone ', 'is_status' => 1],
            ['currency_name' =>'DOP Dominican Republic Peso ', 'is_status' => 1],
            ['currency_name' =>'DZD Algerian Dinar ', 'is_status' => 1],
            ['currency_name' =>'EEK Kroon ', 'is_status' => 1],
            ['currency_name' =>'EGP Egyptian Pound ', 'is_status' => 1],
            ['currency_name' =>'ERN Eritrean Nakfa ', 'is_status' => 1],
            ['currency_name' =>'ETB Ethiopian Birr ', 'is_status' => 1],
            ['currency_name' =>'EUR Euro', 'is_status' => 1],
            ['currency_name' =>'FJD Fiji Dollar ', 'is_status' => 1],
            ['currency_name' =>'FKP Falkland Pound ', 'is_status' => 1],
            ['currency_name' =>'GBP Pound Sterling (United Kingdom Pound) ', 'is_status' => 1],
            ['currency_name' =>'GEL Lari ', 'is_status' => 1],
            ['currency_name' =>'GHS GHS', 'is_status' => 1],
            ['currency_name' =>'GIP Gibraltar Pound ', 'is_status' => 1],
            ['currency_name' =>'GMD Dalasi ', 'is_status' => 1],
            ['currency_name' =>'GNF GNF', 'is_status' => 1],
            ['currency_name' =>'GTQ Quetzal ', 'is_status' => 1],
            ['currency_name' =>'GYD Guyana Dollar ', 'is_status' => 1],
            ['currency_name' =>'HKD Hong Kong Dollar ', 'is_status' => 1],
            ['currency_name' =>'HNL Lempira ', 'is_status' => 1],
            ['currency_name' =>'HRK Croatian Kuna ', 'is_status' => 1],
            ['currency_name' =>'HTG Gourde ', 'is_status' => 1],
            ['currency_name' =>'HUF Forint ', 'is_status' => 1],
            ['currency_name' =>'IDR Rupiah ', 'is_status' => 1],
            ['currency_name' =>'ILS Shekel ', 'is_status' => 1],
            ['currency_name' =>'INR Indian Rupee', 'is_status' => 1],
            ['currency_name' =>'IQD Iraqi Dinar ', 'is_status' => 1],
            ['currency_name' =>'IRR Iranian Rial ', 'is_status' => 1],
            ['currency_name' =>'ISK Icelandic KrÃƒÂ³na ', 'is_status' => 1],
            ['currency_name' =>'JMD Jamaican Dollar ', 'is_status' => 1],
            ['currency_name' =>'JOD Jordanian Dinar ', 'is_status' => 1],
            ['currency_name' =>'JPY Yen ', 'is_status' => 1],
            ['currency_name' =>'KES Kenyan Shilling ', 'is_status' => 1],
            ['currency_name' =>'KGS Kyrgyzstani Som ', 'is_status' => 1],
            ['currency_name' =>'KHR Riel ', 'is_status' => 1],
            ['currency_name' =>'KMF Comorian Franc ', 'is_status' => 1],
            ['currency_name' =>'KPW Democratic Peoples Republic of Korean Won ', 'is_status' => 1],
            ['currency_name' =>'KRW Republic of Korean Won ', 'is_status' => 1],
            ['currency_name' =>'KWD Kuwaiti Dinar ', 'is_status' => 1],
            ['currency_name' =>'KYD Cayman Islands Dollar ', 'is_status' => 1],
            ['currency_name' =>'KZT Tenge ', 'is_status' => 1],
            ['currency_name' =>'LAK Kip ', 'is_status' => 1],
            ['currency_name' =>'LBP Lebanese Pound ', 'is_status' => 1],
            ['currency_name' =>'LKR Sri Lankan Rupee ', 'is_status' => 1],
            ['currency_name' =>'LRD Liberian Dollar ', 'is_status' => 1],
            ['currency_name' =>'LSL Loti ', 'is_status' => 1],
            ['currency_name' =>'LTL Litas ', 'is_status' => 1],
            ['currency_name' =>'LVL Lats ', 'is_status' => 1],
            ['currency_name' =>'LYD Libyan Dinar ', 'is_status' => 1],
            ['currency_name' =>'MAD Moroccan Dirham ', 'is_status' => 1],
            ['currency_name' =>'MDL Moldavian Leu ', 'is_status' => 1],
            ['currency_name' =>'MGA MGA', 'is_status' => 1],
            ['currency_name' =>'MKD Macedonian Dinar ', 'is_status' => 1],
            ['currency_name' =>'MMK Kyat ', 'is_status' => 1],
            ['currency_name' =>'MNT Tugrik ', 'is_status' => 1],
            ['currency_name' =>'MOP Pataca ', 'is_status' => 1],
            ['currency_name' =>'MRO Ouguiya ', 'is_status' => 1],
            ['currency_name' =>'MUR Mauritius Rupee ', 'is_status' => 1],
            ['currency_name' =>'MVR Rufiyaa ', 'is_status' => 1],
            ['currency_name' =>'MWK Malawian Kwacha ', 'is_status' => 1],
            ['currency_name' =>'MXN Mexican New Peso ( Mexican Peso) ', 'is_status' => 1],
            ['currency_name' =>'MYR Ringgit (also known as Malaysian Dollar) ', 'is_status' => 1],
            ['currency_name' =>'MZN  Meticais', 'is_status' => 1],
            ['currency_name' =>'NAD Namibia Dollar ', 'is_status' => 1],
            ['currency_name' =>'NGN Naira ', 'is_status' => 1],
            ['currency_name' =>'NIO  Cordobas', 'is_status' => 1],
            ['currency_name' =>'NOK Norwegian Krone ', 'is_status' => 1],
            ['currency_name' =>'NPR Nepalese Rupee ', 'is_status' => 1],
            ['currency_name' =>'NZD New Zealand Dollar ', 'is_status' => 1],
            ['currency_name' =>'OMR Omani Rial ', 'is_status' => 1],
            ['currency_name' =>'PAB Balboa ', 'is_status' => 1],
            ['currency_name' =>'PEN New Sol ', 'is_status' => 1],
            ['currency_name' =>'PGK Kina ', 'is_status' => 1],
            ['currency_name' =>'PHP Philippines Peso ', 'is_status' => 1],
            ['currency_name' =>'PKR Pakistani Rupee ', 'is_status' => 1],
            ['currency_name' =>'PLN New Zloty ', 'is_status' => 1],
            ['currency_name' =>'PYG Guarani ', 'is_status' => 1],
            ['currency_name' =>'QAR Qatari Riyal ', 'is_status' => 1],
            ['currency_name' =>'RON  New Lei', 'is_status' => 1],
            ['currency_name' =>'RSD  Dinars', 'is_status' => 1],
            ['currency_name' =>'RUB  Rubles', 'is_status' => 1],
            ['currency_name' =>'RWF Rwandan Franc ', 'is_status' => 1],
            ['currency_name' =>'SAR Saudi Riyal ', 'is_status' => 1],
            ['currency_name' =>'SBD Solomon Islands Dollar ', 'is_status' => 1],
            ['currency_name' =>'SCR Seychelles Rupee ', 'is_status' => 1],
            ['currency_name' =>'SDG Sudanese Pound ', 'is_status' => 1],
            ['currency_name' =>'SEK Swedish Krona ', 'is_status' => 1],
            ['currency_name' =>'SGD Singapore Dollar ', 'is_status' => 1],
            ['currency_name' =>'SHP St Helena Pound ', 'is_status' => 1],
            ['currency_name' =>'SLL Leone ', 'is_status' => 1],
            ['currency_name' =>'SOS Somali Shilling ', 'is_status' => 1],
            ['currency_name' =>'SRD  Dollars', 'is_status' => 1],
            ['currency_name' =>'STD Dobra ', 'is_status' => 1],
            ['currency_name' =>'SYP Syrian Pound ', 'is_status' => 1],
            ['currency_name' =>'SZL Lilangeni ', 'is_status' => 1],
            ['currency_name' =>'THB Baht ', 'is_status' => 1],
            ['currency_name' =>'TJS TJS', 'is_status' => 1],
            ['currency_name' =>'TMT TMT', 'is_status' => 1],
            ['currency_name' =>'TND Tunisian Dinar ', 'is_status' => 1],
            ['currency_name' =>'TOP Paanga ', 'is_status' => 1],
            ['currency_name' =>'TRL New Turkish Lira ', 'is_status' => 1],
            ['currency_name' =>'TRY Turkish Lira', 'is_status' => 1],
            ['currency_name' =>'TTD Trinidad and Tobago Dollar ', 'is_status' => 1],
            ['currency_name' =>'TWD Taiwan Dollar ', 'is_status' => 1],
            ['currency_name' =>'TZS Tanzanian Shilling ', 'is_status' => 1],
            ['currency_name' =>'UAH Hryvna ', 'is_status' => 1],
            ['currency_name' =>'UGX UGX', 'is_status' => 1],
            ['currency_name' =>'USD United States Dollar ', 'is_status' => 1],
            ['currency_name' =>'UYU Uruguayan Peso ', 'is_status' => 1],
            ['currency_name' =>'UZS Uzbekistani Som ', 'is_status' => 1],
            ['currency_name' =>'VEF Bolivar Fuerte ', 'is_status' => 1],
            ['currency_name' =>'VND Viet Nam DÃƒÂ´ng ', 'is_status' => 1],
            ['currency_name' =>'VUV Vatu ', 'is_status' => 1],
            ['currency_name' =>'WST Tala ', 'is_status' => 1],
            ['currency_name' =>'XAF Franc de la CommunautÃƒÂ© financiÃƒÂ¨re africaine ', 'is_status' => 1],
            ['currency_name' =>'XCD East Caribbean Dollar ', 'is_status' => 1],
            ['currency_name' =>'XOF West African Franc ', 'is_status' => 1],
            ['currency_name' =>'XPF Franc des Comptoirs franÃƒÂ§ais du Pacifique ', 'is_status' => 1],
            ['currency_name' =>'YER Yemeni Riyal ', 'is_status' => 1],
            ['currency_name' =>'ZAR Rand ', 'is_status' => 1],
            ['currency_name' =>'ZMK Zambian Kwacha ', 'is_status' => 1],
            ['currency_name' =>'ZWL ', 'is_status' => 1]
        ];

        foreach ($currencies as $key => $value) {
            Currency::create($value);
        }
    }
}
